Glaz8212/FrozenTrust

Assets/Scripts/LSH/GameManager.cs
Assets/Scripts/LSH/GameManager.cs.meta
Assets/Scripts/LSH/GameSceneManager.cs
Assets/Scripts/LSH/GameSceneManager.cs.meta
Assets/Scripts/LSH/UIManager.cs
Assets/Scripts/LSH/UIManager.cs.meta

게임 매니저 스크립트 3종류 추가
-GameManager
-GameSceneManager
-UIManager

[Add] GameManagers

---

Assets/DEV/LSH/Scenes/DevScene.unity
Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/LSH/Scripts/GameSceneManager.cs
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

[Feat] 
PlayerEnemyReroll - 역할 배정 소스코드
Check Win - 플레이어 승패 판정
State - 게임 상태 업데이트
Timer - 타이머 동기화

[Feat] PlayerEnemyReroll, Check Win, State, Timer

---

Assets/DEV/LSH/Prefabs/Item.prefab
Assets/DEV/LSH/Scenes/DevScene.unity
Assets/DEV/LSH/Scripts/ItemPrefab.cs
Assets/DEV/LSH/Scripts/ItemPrefab.cs.meta
Assets/DEV/LSH/Scripts/ItemTester.cs
Assets/DEV/LSH/Scripts/ItemTester.cs.meta
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

[Feat] UIScripts

---

Assets/DEV/JHS/Prefabs/Player01.prefab
Assets/DEV/JHS/Scripts/PlayerInteraction.cs

[feat] 플레이어와 오브젝트 상호작용 

---

Assets/DEV/LSH/Prefabs/Item.prefab
Assets/DEV/LSH/Scenes/DevScene.unity
Assets/DEV/LSH/Scenes/TestScene1.unity
Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/LSH/Scripts/GameSceneManager.cs
Assets/DEV/LSH/Scripts/InvenTester.cs
Assets/DEV/LSH/Scripts/ItemTester.cs
Assets/DEV/LSH/Scripts/ItemTester.cs.meta
Assets/DEV/LSH/Scripts/PlayerInventory.cs

Remove및 Checkwin 조건 수정, ItemTester 함수 부분 수정

[Feat] Remove추가

---

Assets/DEV/LSH/Prefabs/Inventory_v1.prefab
Assets/DEV/LSH/Prefabs/Inventory_v1.prefab.meta
Assets/DEV/LSH/Scripts/GameManager.cs

[Feat] Inventory Prefab, GameManager

---

Assets/DEV/LSH/Prefabs/Inventory_v1.prefab
Assets/DEV/LSH/Prefabs/WeaponBar_v1.prefab
Assets/DEV/LSH/Prefabs/WeaponBar_v1.prefab.meta
Assets/DEV/LSH/Scripts/GameSceneManager.cs
Assets/DEV/LSH/Scripts/InvenTester.cs
Assets/DEV/LSH/Scripts/PlayerInventory.cs

UI 수정
GameSceneManager nowPlayer 변수 생성

[Fix] UI 수정

---

Assets/DEV/YJE/Prefabs/ClearShot Camera.prefab
Assets/Resources/JHS/Player01.prefab

[feat] ClearShot Camera prefab 수정

---

Assets/DEV/JHS/Scripts/PlayerInteraction.cs
Assets/DEV/JHS/Scripts/PlayerStatus.cs

플레이어 상호작용 문법 오류 수정
플레이어 미션 박스 상호작용 추가
플레이어 상태 public

[feat] 플레이어 상호작용 및 상태 코드 수정

---

Assets/DEV/Test/1stNetworkTest/GameScene.unity

- BaseCamp 입구의 trigger 추가
- trigger에 BaseEnvironment.cs 추가

[feat] GameScene BaseCamp Trigger 추가

---

Assets/DEV/JHS/Scripts/NamePrint.cs
Assets/DEV/JHS/Scripts/PlayerInteraction.cs
Assets/DEV/JHS/Scripts/PlayerStatus.cs

플레이어 시작 시 환경 요소 cold로 변경
플레이어 이름 생성 시 딜레이 추가 
아이템 상호작용 패턴 보강
환경에 따른 플레이어 상태 로직 수정

[feat] 플레이어 상호 작용 및 환경 로직 변경

---

Assets/DEV/LSH/Scenes/DevScene.unity
Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/LSH/Scripts/GameSceneManager.cs
Assets/DEV/LSH/Scripts/UIManager.cs

[Feat] GameSceneManager

---

Assets/DEV/LSH/Scenes/DevScene.unity
Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/LSH/Scripts/PlayerInventory.cs
Assets/DEV/LSH/Scripts/UIManager.cs

[Fix] Scripts Fix

---

Assets/DEV/LSH/Scripts/Item.cs

해당 오브젝트의 소유권이 없어서 삭제가 되지않아
Item스크립트에서 RPC함수로 마스터 클라이언트에 삭제 요청

[Update] Item

---

Assets/DEV/JHS/Scripts/NamePrint.cs
Assets/DEV/JHS/Scripts/PlayerInteraction.cs

[feat] 플레이어 네임 수정, 네트워크 상호작용 코드 수정

---

Assets/DEV/LSH/Prefabs/Canvas.prefab
Assets/DEV/LSH/Prefabs/GameManager.prefab
Assets/DEV/LSH/Prefabs/GameManager.prefab.meta
Assets/DEV/LSH/Prefabs/GameSceneManager.prefab
Assets/DEV/LSH/Prefabs/GameSceneManager.prefab.meta
Assets/DEV/LSH/Scripts/UIManager.cs
Assets/DEV/Test/1stNetworkTest/GameScene.unity
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

[Feat] Prefab Create, UIManager

---

Assets/DEV/JHS/Scripts/PlayerInteraction.cs
Assets/DEV/JHS/Scripts/PlayerStatus.cs

플레이어 상태 public으로 수정
상호작용 코드에 photonView를 추가하여 본인이 상호작용 가능한 상태 일 때 만 상호작용 가능
플레이어 스탯 코드 최적화

[feat] 플레이어 스탯 코드 최적화 및 상호작용 코드 수정

---

Assets/DEV/Test/1stNetworkTest/GameScene.unity

- Object pool 사용을 위한 ItemController prefab 적용

[faat] GameScene ItemController 적용

---

Assets/DEV/JHS/Prefabs/Hammer.prefab
Assets/DEV/JHS/Prefabs/Hammer.prefab.meta
Assets/DEV/JHS/Prefabs/Player01.prefab
Assets/DEV/JHS/Prefabs/WeaponHammer.prefab
Assets/DEV/JHS/Prefabs/WeaponHammer.prefab.meta
Assets/DEV/JHS/Scenes/PlayerTestScene.unity
Assets/DEV/JHS/Scripts/NamePrint.cs
Assets/DEV/JHS/Scripts/PlayerAttacker.cs
Assets/DEV/JHS/Scripts/PlayerInteraction.cs
Assets/DEV/JHS/Scripts/WeaponState.cs
Assets/Resources/JHS/Player01.prefab
Assets/Resources/JHS/WeaponAxe 1.prefab
Assets/Resources/JHS/WeaponAxe 1.prefab.meta
Assets/Resources/JHS/WeaponHammer.prefab
Assets/Resources/JHS/WeaponHammer.prefab.meta

플레이어 무기 탈착 적용
플레이어 상호작용 로직 수정
플레이어 공격 로직 수정
무기 콜라이더 참조 null 추가

[feat] 플레이어 코드 수정 및 무기 상호작용

---

Assets/DEV/YJE/BoxInventory.cs
Assets/DEV/YJE/ClickedItem.cs

- Inventory에서 Ui의 업데이트가 제대로 진행되지 않는 부분을 수정 (UpdateItem())
+ 새로운 환경에서 테스트 필요

[feat] Item Box Inventory 수정

---

Assets/DEV/LSH/Prefabs/Canvas.prefab
Assets/DEV/LSH/Prefabs/PlayerStatusBar.prefab
Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/LSH/Scripts/UIManager.cs
Assets/DEV/Test/1stNetworkTest/GameScene.unity
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

GameManager에서 배신자 리스트를 RPC함수로 전송
UI에서 배신자 목록 표시

[Feat] UIList

---

Assets/DEV/YJE/ClickedItem.cs
Assets/DEV/YJE/ItemBox.prefab
Assets/DEV/YJE/Prefabs/BoxItem.prefab
Assets/DEV/YJE/Prefabs/R_Grass.prefab
Assets/DEV/YJE/Prefabs/R_Rock.prefab
Assets/DEV/YJE/Prefabs/R_Tree.prefab

Resource Prefab trigger Collider위치 수정

[fix] Resource Prefab trigger Collider 위치 수정

---

Assets/DEV/LSH/Prefabs/Canvas.prefab
Assets/DEV/LSH/Scenes/DevScene.unity
Assets/DEV/LSH/Scripts/UIManager.cs
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

[Fix] UIManager, Canvas수정

---

Assets/DEV/LSH/Prefabs/Canvas.prefab
Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/LSH/Scripts/GameSceneManager.cs
Assets/DEV/LSH/Scripts/UIManager.cs

UI퀘스트 리스트 출력문 변경
게임 매니저 게임 종료시 코루틴 중지와 연결 끊기
씬매니저 패배 조건 수정 및 참조 변경

[Fix] UI, Game, SceneManager

---

Assets/DEV/Test/1stNetworkTest/GameScene.unity
Assets/DEV/YJE/BoxInventory.cs
Assets/DEV/YJE/PlayerClickedItem.cs
Assets/DEV/YJE/PlayerItemBtn.cs

- ItemBox Inventory에서 제거 시 Item 개수 오류 수정
- Item 사용 시 Player의 허기 증가

[fix] ItemBox Inventory 개수 오류 수정 / [feat] Item 사용 시 Player의 허기 증가

---

Assets/DEV/LSH/Scripts/UIManager.cs

[Update] UIManager

---

Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/LSH/Scripts/GameSceneManager.cs

[Feat] Manager

---

Assets/DEV/Test/1stNetworkTest/GameScene.unity
Assets/DEV/YJE/MissionBoxInventory.cs
Assets/DEV/YJE/MissionClicekedItem.cs
Assets/DEV/YJE/Pool/ItemController.cs
Assets/DEV/YJE/Prefabs/R_Grass.prefab
Assets/DEV/YJE/Prefabs/R_Rock.prefab
Assets/DEV/YJE/Prefabs/R_Tree.prefab
Assets/DEV/YJE/Scripts/PlayerClickedItem.cs
ProjectSettings/TagManager.asset

[fix] Tags 수정 + GameScene 수정

---

Assets/DEV/LSH/Scripts/GameSceneManager.cs

[Feat] NickName Hide

---

Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/LSH/Scripts/GameSceneManager.cs

[Fix] Code Fix

---

Assets/DEV/YJE/MissionBoxInventory.cs
Assets/DEV/YJE/Scripts/PlayerClickedItem.cs
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

- MissionBox에서 제거 시 아이템 복제되는 현상 수정

[fix] Mission Box Inventory의 오류 수정

---

Assets/DEV/LSH/Scripts/GameSceneManager.cs

비활성화된 오브젝트를 찾지못해 List변수를 만들어 담아주는 형식으로 변경

[Fix] FindObjectsOfType

---

Assets/DEV/YJE/ItemBox.prefab
Assets/DEV/YJE/MissionBox.prefab
Assets/DEV/YJE/MissionBoxBtn.cs
Assets/DEV/YJE/MissionBoxBtn.cs.meta
Assets/DEV/YJE/MissionBoxInventory.cs
Assets/DEV/YJE/MissionClicekedItem.cs
Assets/DEV/YJE/MissionController.cs
Assets/DEV/YJE/MissionController.prefab
Assets/DEV/YJE/Prefabs/R_Grass.prefab
Assets/DEV/YJE/Prefabs/R_Rock.prefab
Assets/DEV/YJE/Prefabs/R_Tree.prefab
Assets/DEV/YJE/Scripts/PlayerClickedItem.cs
Assets/DEV/YJE/SetMissionUI.cs
Assets/DEV/YJE/SetMissionUI.cs.meta
Assets/DEV/YJE/ShowQuest.prefab
Assets/DEV/YJE/ShowQuest.prefab.meta

1. Mission Box
- Mission 조건 완료 시 Apply 버튼 활성화
- Apply 버튼 클릭 시 Mission Clear 여부 판단
- Mission1 완료 시 Mission 2 생성
2. bug
- Mission의 조건 완료 후 Apply 버튼을 각 Player마다 눌러서 각각 다음 Mission Box를 활성화 해야하는 오류 발생
- Apply버튼의 활성화는 공유 완료
- Mission의 Clear 여부가 공유되지 않는 것으로 추정
- Mission1 Clear 후 Mission2가 활성화, 그 후 PlayerInteration의 Current Collider와 MissionController가 MissionBox1에서 변하지 않는 것을 확인
- 이후 다른 상호작용도 안되는 것으로 추정
- trigger로 변경

[fix/feat] Resource Prefab Collider 변경 + Mission Controller의 Mission 구현 + [feat] Mission 로직 추가

---

Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/LSH/Scripts/GameSceneManager.cs
Assets/DEV/Test/1stNetworkTest/GameScene.unity
Assets/DEV/YJE/MissionBox.cs
Assets/DEV/YJE/MissionBox.prefab
Assets/DEV/YJE/MissionBoxInventory.cs
Assets/DEV/YJE/MissionController.cs
Assets/DEV/YJE/MissionController.prefab
Assets/DEV/YJE/Pool/ItemController.cs
Assets/DEV/YJE/SetMissionUI.cs

1. Mission Box의 Quest를 UI로 출력하도록 수정
2. MissionBox의 Mission 버튼 활성/비활성화 상태 공유
3. Mission 의 Clear 상태 공유
4. 생존자가 승리한 경우 Ending 추가
5. 배신자가 승리한 경우 Ending 추가

[feat] Mission Box UI setting 수정 + Mission Box 로직 수정 + GameSecen Ending 추가

---

Assets/DEV/LSH/Scripts/GameSceneManager.cs

List에 값이 들어가지 않아 Clear()삭제 후 테스트

[Test] Test FindNameUI

---

Assets/DEV/YJE/Scripts/ResourceController.cs
Assets/DEV/YJE/SetMissionUI.cs
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

- ResourceController의 Die함수 RPC 변경
- SetMissionUI 코루틴 추가

[fix] RPC 함수로 변경 + SetMissionUI 코루틴 추가

---

Assets/DEV/Test/1stNetworkTest/GameScene.unity
ProjectSettings/TagManager.asset

[fix] Resource tags 추가

---

Assets/DEV/YJE/Scripts/CameraController.cs
Assets/DEV/YJE/Scripts/PlayerCameraController.cs
Assets/DEV/YJE/Scripts/ResourceController.cs

- ResourceController에서 tag 수정
-  Camera 참조 수정

[fix] ResourceController에서 tag 수정 + Camera 참조 수정

---

Assets/DEV/YJE/MissionController.cs
Assets/DEV/YJE/Scripts/PlayerClickedItem.cs

[fix] MissionBox Bug 수정

---

Assets/DEV/LSH/Scripts/GameManager.cs
Assets/DEV/YJE/SetMissionUI.cs

MissionBox UI Setting Error 수정

[fix] MissionBox UI Setting Error 수정

---

Assets/DEV/YJE/MissionController.cs
Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset

[fix] Mission Box Button

---

Assets/DEV/JHS/Scripts/PlayerInteraction.cs

[Fix] PlayerInteraction

---

Assets/DEV/JHS/Prefabs/Signs.prefab
Assets/DEV/JHS/Prefabs/Signs.prefab.meta
Assets/DEV/JHS/Scenes/PlayerTestScene.unity
Assets/DEV/JHS/Scripts/PlayerAttacker.cs
Assets/DEV/LWS/Prefabs/Elk.prefab
Assets/DEV/Test/1stNetworkTest/GameScene.unity
Assets/DEV/YJE/Prefabs/R_Grass.prefab
Assets/DEV/YJE/Prefabs/R_Rock.prefab
Assets/DEV/YJE/Prefabs/R_Tree.prefab
Assets/Resources/JHS/Signs.prefab
Assets/Resources/JHS/Signs.prefab.meta

자원 체력 증가  
야생동물 체력 증가
표지판 생성
무기 배치 증가
미션 및 박스 인벤토리 오픈 시 공격 불가 로직 추가

[feat] 게임 씬 수정 및 공격 로직 수정

---

Assets/DEV/LSH/Scripts/GameSceneManager.cs

[fix] teleport
